feat(BitBucket): add BitBucket server docs
mend/renovate-ce-ee pull request #411
Opened 2023-12-22 12:51 UTC by nabeelsaabna

2023-12-22 13:00 UTC, rarkins requested changes

2023-12-22 13:06 UTC, nabeelsaabna commented on docs/configure-renovate-bitbucket-server.md
> +Refer to [LINK] for a full list of Renovate CE/EE server variables.
We don't this file yet!

2023-12-22 13:07 UTC, nabeelsaabna commented on docs/configure-renovate-bitbucket-server.md
> +> docker-compose -f docker-compose-bitbucket.yaml up  [Check this]
Not sure what should this be :-/

2023-12-22 13:12 UTC, nabeelsaabna commented on docs/configure-renovate-bitbucket-server.md
> +Authorization: <MEND_RNV_SERVER_API_SECRET>
fixed by separate commit

2023-12-22 13:33 UTC, nabeelsaabna commented on docs/configure-renovate-bitbucket-server.md
> +> docker-compose -f docker-compose-bitbucket.yaml up  [Check this]
will need to add a new file, prefer to keep it for a another PR

2023-12-22 13:33 UTC, nabeelsaabna commented on docs/configure-renovate-bitbucket-server.md
> +Refer to [LINK] for a full list of Renovate CE/EE server variables.
will need to add a new file, prefer to keep it for a another PR

2023-12-24 09:03 UTC, Gabriel-Ladzaretti commented on docs/configure-renovate-bitbucket-server.md
> +[POST]   http://<RENOVATE-SERVER-URL>/api/sync
.

2023-12-27 09:30 UTC, merged

2025-08-11 10:12 UTC, OBITOONDEADO1MZ approved these changes