Added docs for Postgres DB configuration
mend/renovate-ce-ee pull request #434
Opened 2024-01-23 16:32 UTC by justo-mend

2024-01-23 16:42 UTC, rarkins requested changes

2024-01-23 16:42 UTC, rarkins commented on docs/configure-postgres-db.md
> +| PGPORT | Host Port for the PostgreSQL instance |
Do any of the above have default values so are optional?

2024-01-23 16:42 UTC, rarkins commented on docs/configure-postgres-db.md
> +      replicas: 2
Leave HA separate

2024-01-24 11:33 UTC, justo-mend commented on docs/configure-postgres-db.md
> +      replicas: 2
Will remove "deploy" config.

2024-01-24 11:33 UTC, justo-mend commented on docs/configure-postgres-db.md
> +# Postgres DB Configuration
Will put that on the TODO list.

2024-01-24 12:32 UTC, nabeelsaabna submitted a review, later dismissed

2024-01-24 14:26 UTC, rarkins requested changes

2024-01-24 14:26 UTC, rarkins commented on docs/configure-postgres-db.md
> +An example of starting a PostgreSQL DB server container in a Docker Compose file is shown below.
```suggestion

An example of using a PostgreSQL DB server container with Docker Compose is shown below.
```

2024-01-24 14:26 UTC, rarkins commented on docs/configure-postgres-db.md
> +| PGPORT | Host Port for the PostgreSQL instance |
```suggestion
| Environment variable name  | Description                                             |
|----------------------------|---------------------------------------------------------|
| MEND_RNV_DATA_HANDLER_TYPE | Set to ‘postgresql’ to use a PostgreSQL database        |
| PGDATABASE                 | Name of the database instance. Eg. ‘postgres’           |
| PGUSER                     | Postgres User name. Must have Create Schema permission. |
| PGPASSWORD                 | Postgres User password                                  |
| PGHOST                     | Host name of the PostgreSQL instance                    |
| PGPORT                     | Host Port for the PostgreSQL instance                   |
```

2024-01-24 14:27 UTC, rarkins commented on docs/configure-postgres-db.md
> +```
```suggestion

```
```

2024-01-24 14:29 UTC, rarkins approved these changes

2024-01-24 15:03 UTC, nabeelsaabna approved these changes

2024-01-24 15:03 UTC, merged