docs/examples
mend/renovate-ce-ee pull request #456
Opened 2024-02-11 14:24 UTC by justo-mend

2024-02-11 14:28 UTC, rarkins requested changes
This needs an accompanying documentation to describe it

2024-02-11 14:36 UTC, rarkins commented on examples/renovate-ee-simple.yml
These files are under an "examples" folder but it seems like they'd benefit from an extra folder layer, such as "docker-compose" here.

2024-02-11 15:09 UTC, justo-mend commented on examples/renovate-ee-simple.yml
Good thinking. Pushed in new commit.

2024-02-11 17:21 UTC, rarkins commented on examples/env/github.env
Where are these two env files referenced?

2024-02-11 17:22 UTC, rarkins requested changes
This still feels too much like a "file dump" and not a cohesive example. Ideally has:
- Markdown docs describing what each example is for
- References between files, e.g. to the .env files

2024-02-11 19:12 UTC, justo-mend commented on examples/env/github.env
There were referenced in earlier versions of the ee yml. But they are no longer directly linked. I could remove them. Or, add example config for the other platforms alongside the github one.

2024-02-11 19:13 UTC, justo-mend commented
> This still feels too much like a "file dump" and not a cohesive example. Ideally has:
> 
> * Markdown docs describing what each example is for
> * References between files, e.g. to the .env files

Good idea. I'll create a readme at the 'examples' level.

2024-02-11 19:47 UTC, rarkins commented on examples/env/github.env
If we have undocumented examples then it risks being more of a confusion than help. Would be best to have them tied together with some text

2024-02-11 20:11 UTC, justo-mend commented on examples/env/github.env
I've added some text to the new Examples readme. Maybe that helps.

2024-02-13 07:40 UTC, rarkins approved these changes

2024-02-13 07:40 UTC, merged