feat: update charts
mend/renovate-ce-ee pull request #457
Opened 2024-02-12 10:53 UTC by nabeelsaabna

2024-03-17 12:35 UTC, nabeelsaabna commented on helm-charts/mend-renovate-ee/templates/server-deployment.yaml
> +            - name: { { .Release.Name } }-database-volume
all other places it's `{{ .Release.Name }}` without spaces
spaces maybe a bug, but regardless i wanted to make it consistent

2024-03-17 12:40 UTC, nabeelsaabna commented on helm-charts/mend-renovate-ee/values.yaml
> +    # if to use PostgreSQL, if unset SQLite will be used instead
done 👍

2024-03-17 15:16 UTC, viceice reviewed
you should use a helm readme generator to automatically update the readme from values.

- https://github.com/bitnami/readme-generator-for-helm

2024-03-17 15:16 UTC, viceice commented on helm-charts/mend-renovate-ce/values.yaml
> +  # valid values: "github", "gitlab" or "bitbucket-server"
should be sorted alphabetically

2024-03-17 15:16 UTC, viceice commented on helm-charts/mend-renovate-ee/values.yaml
> +  # valid values: "github", "gitlab" or "bitbucket-server"
Same here.

2024-03-18 08:20 UTC, nabeelsaabna commented on helm-charts/mend-renovate-ce/values.yaml
> +  # valid values: "github", "gitlab" or "bitbucket-server"
done

2024-03-18 08:20 UTC, nabeelsaabna commented on helm-charts/mend-renovate-ee/values.yaml
> +  # valid values: "github", "gitlab" or "bitbucket-server"
done

2024-03-18 08:21 UTC, nabeelsaabna commented
> you should use a helm readme generator to automatically update the readme from values.
> 
> * https://github.com/bitnami/readme-generator-for-helm

👍 
will do it in a standalone PR

2024-03-18 08:31 UTC, viceice approved these changes
I hope you tested the indention changes

2024-03-19 09:21 UTC, PhilipAbed approved these changes

2024-03-19 09:22 UTC, merged

2024-03-19 09:27 UTC, viceice requested changes

2024-03-19 09:27 UTC, viceice commented on helm-charts/mend-renovate-ce/templates/deployment.yaml
> +      {{- end }}
```suggestion
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
```

2024-03-19 09:28 UTC, viceice requested changes
@nabeelsaabna sorry for not seeing this before

2024-03-19 09:28 UTC, viceice commented on helm-charts/mend-renovate-ee/templates/server-deployment.yaml
> +      {{- if .Values.renovateServer.imagePullSecrets }}
same here

2024-03-19 09:28 UTC, viceice commented on helm-charts/mend-renovate-ee/templates/worker-deployment.yaml
> +      {{- if .Values.renovateWorker.imagePullSecrets }}
same here

2024-03-19 12:39 UTC, viceice commented
- #472