docs: add documentation for Job Logs APIs
mend/renovate-ce-ee pull request #505
Opened 2024-05-16 11:21 UTC by justo-mend

Added documentation for Job Logs APIs

2024-05-16 17:29 UTC, marcus-griep-simplisafe reviewed
Suggestions for two suspected typos

2024-05-16 17:29 UTC, marcus-griep-simplisafe commented on docs/job-logs-apis.md
> +| [Get Job Logs by Repo](#get-job-logs-by-repo)   | [GET] /api/repos/{org}/{repo}/-/jobs/<latest\|{jobId}> |                                 |
Unintentional extra long cell?
```suggestion
| [Get Job Logs by Repo](#get-job-logs-by-repo)   | [GET] /api/repos/{org}/{repo}/-/jobs/<latest\|{jobId}> |                                 |
```

2024-05-19 05:51 UTC, nabeelsaabna requested changes

2024-05-19 05:51 UTC, nabeelsaabna commented on docs/job-logs-apis.md
> +  Authorization: renovateapi
```suggestion
  Authorization: Bearer renovateapi
  or
  Authorization: renovateapi
```

2024-05-19 05:51 UTC, nabeelsaabna approved these changes

2024-05-19 05:53 UTC, merged