feat: Add option to store cache in ramdisk/tmpfs 🔥
mend/renovate-ce-ee pull request #524
Opened 2024-06-24 23:08 UTC by oscrx

Add option to store cache in ramdisk/tmpfs 🔥

2024-06-24 23:13 UTC, oscrx commented
It might even be a good default... But it might mess with some people's memory limits.
Memory increase is not shocking though, but the speeeeeeed is 🚀
<img width="768" alt="afbeelding" src="https://github.com/mend/renovate-ce-ee/assets/6731096/d2c2a6f7-0e69-49e0-8911-32ed065c50c0">

2024-07-01 09:07 UTC, nabeelsaabna requested changes
add comments

2024-07-01 09:07 UTC, nabeelsaabna commented on helm-charts/mend-renovate-ce/values.yaml
> +##
```suggestion
## cachePersistence.enabled takes precedence, make sure its disabled
##
```

2024-07-01 09:07 UTC, nabeelsaabna commented on helm-charts/mend-renovate-ee/values.yaml
> +##
```suggestion
## cachePersistence.enabled takes precedence, make sure its disabled
##
```

2024-07-01 09:07 UTC, nabeelsaabna commented on helm-charts/mend-renovate-ce/Chart.yaml
> +version: 7.4.0
```suggestion
version: 7.5.0
```

2024-07-01 09:07 UTC, nabeelsaabna commented on helm-charts/mend-renovate-ee/Chart.yaml
> +version: 1.4.0
```suggestion
version: 1.5.0
```

2024-07-09 14:39 UTC, oscrx commented
Sorry, this PR slipped my mind, let me know if I need to squash or rebase something :)

2024-07-11 14:55 UTC, nabeelsaabna approved these changes

2024-07-11 14:56 UTC, merged